defaults:
  - hydra/job_logging : default     # Job's logging config
  - hydra/launcher: basic           # Launcher config
  - hydra/sweeper: basic            # Sweeper config
  - hydra/output: default           # Output directory
  
name: "Basic Config"
batch_size: 32
learning_rate: 1e-3
gpus: 1
dataset: "./data/fractaldb_cat60_ins1000"
model: "efficientnet_b0"
num_workers: 12
epochs: 100